### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by arxk9** [USC-ACTLab/crazyswarm#135]
When trying to build the project with ./build.sh on ubuntu 16.04 and ros-kinetic, we get this error:
```
####
#### Running command: "make -j8 -l8" in "/home/um/crazyswarm/ros_ws/build"
####
[  0%] Built target std_msgs_generate_messages_cpp
[  1%] Built target crazyflie_controller
[  1%] Built target geometry_msgs_generate_messages_cpp
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by '/home/um/crazyswarm/ros_ws/devel/lib/liblibobjecttracker.so'.  Stop.
[  6%] Built target ViconDataStreamSDK_CPP
CMakeFiles/Makefile2:1053: recipe for target 'externalDependencies/libobjecttracker/CMakeFiles/libobjecttracker.dir/all' failed
make[1]: *** [externalDependencies/libobjecttracker/CMakeFiles/libobjecttracker.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  7%] Built target quadrotor_teleop
[ 11%] Built target crazyflie_cpp
[ 11%] Built target _crazyflie_driver_generate_messages_check_deps_GoTo
[ 11%] Built target _crazyflie_driver_generate_messages_check_deps_AddCrazyflie
[ 11%] Built target _crazyflie_driver_generate_messages_check_deps_Takeoff
[ 11%] Built target _crazyflie_driver_generate_messages_check_deps_Hover
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
```

This probably has something to do with libmotioncapture, but we don't really know how to resolve it.

**Comment by whoenig** [comment]
I have not seen this issue before and I am not sure what `libproj.so` is. In `ros_ws` folder, could you run `catkin_make -j1 -k` twice and post the output of the second run?

**Comment by arxk9** [comment]
Absolutely! Here's the output of the second run:
```
Base path: /home/um/crazyswarm/ros_ws
Source space: /home/um/crazyswarm/ros_ws/src
Build space: /home/um/crazyswarm/ros_ws/build
Devel space: /home/um/crazyswarm/ros_ws/devel
Install space: /home/um/crazyswarm/ros_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/um/crazyswarm/ros_ws/build"
####
####
#### Running command: "make -j1 -k" in "/home/um/crazyswarm/ros_ws/build"
####
[  4%] Built target crazyflie_cpp
[  5%] Built target listLogVariables
[  6%] Built target scan
[  7%] Built target listParams
[  8%] Built target listMemories
[  9%] Built target reboot
[ 10%] Built target battery
[ 12%] Built target version
[ 15%] Built target console
[ 16%] Built target flash
[ 21%] Built target ViconDataStreamSDK_CPP
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by '/home/um/crazyswarm/ros_ws/devel/lib/liblibmotioncapture.so'.
make[2]: Target 'externalDependencies/libmotioncapture/CMakeFiles/libmotioncapture.dir/build' not remade because of errors.
CMakeFiles/Makefile2:904: recipe for target 'externalDependencies/libmotioncapture/CMakeFiles/libmotioncapture.dir/all' failed
make[1]: *** [externalDependencies/libmotioncapture/CMakeFiles/libmotioncapture.dir/all] Error 2
[ 22%] Built target ViconDataStreamSDK_CPPTest
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by '/home/um/crazyswarm/ros_ws/devel/lib/liblibobjecttracker.so'.
make[2]: Target 'externalDependencies/libobjecttracker/CMakeFiles/libobjecttracker.dir/build' not remade because of errors.
CMakeFiles/Makefile2:1053: recipe for target 'externalDependencies/libobjecttracker/CMakeFiles/libobjecttracker.dir/all' failed
make[1]: *** [externalDependencies/libobjecttracker/CMakeFiles/libobjecttracker.dir/all] Error 2
[ 23%] Built target quadrotor_teleop
[ 24%] Built target crazyflie_controller
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_GoTo
[ 24%] Built target std_msgs_generate_messages_cpp
[ 24%] Built target geometry_msgs_generate_messages_cpp
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_Takeoff
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_AddCrazyflie
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_Hover
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_crtpPacket
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_Land
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_LogBlock
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_SetGroupMask
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_StartTrajectory
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_GenericLogData
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_sendPacket
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_TrajectoryPolynomialPiece
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_UpdateParams
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_Position
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_UploadTrajectory
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_RemoveCrazyflie
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_FullState
[ 24%] Built target _crazyflie_driver_generate_messages_check_deps_Stop
[ 24%] Generating C++ code from crazyflie_driver/GenericLogData.msg
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:80: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/GenericLogData.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/GenericLogData.h] Error 1
[ 25%] Generating C++ code from crazyflie_driver/crtpPacket.msg
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:86: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/crtpPacket.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/crtpPacket.h] Error 1
[ 25%] Generating C++ code from crazyflie_driver/Position.msg
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:93: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Position.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Position.h] Error 1
[ 26%] Generating C++ code from crazyflie_driver/Hover.msg
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:100: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Hover.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Hover.h] Error 1
[ 27%] Generating C++ code from crazyflie_driver/FullState.msg
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:112: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/FullState.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/FullState.h] Error 1
[ 27%] Generating C++ code from crazyflie_driver/TrajectoryPolynomialPiece.msg
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:118: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/TrajectoryPolynomialPiece.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/TrajectoryPolynomialPiece.h] Error 1
[ 29%] Generating C++ code from crazyflie_driver/LogBlock.msg
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:124: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/LogBlock.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/LogBlock.h] Error 1
[ 30%] Generating C++ code from crazyflie_driver/SetGroupMask.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:131: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/SetGroupMask.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/SetGroupMask.h] Error 1
[ 30%] Generating C++ code from crazyflie_driver/Stop.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:138: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Stop.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Stop.h] Error 1
[ 31%] Generating C++ code from crazyflie_driver/StartTrajectory.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:145: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/StartTrajectory.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/StartTrajectory.h] Error 1
[ 31%] Generating C++ code from crazyflie_driver/RemoveCrazyflie.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:152: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/RemoveCrazyflie.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/RemoveCrazyflie.h] Error 1
[ 32%] Generating C++ code from crazyflie_driver/AddCrazyflie.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:160: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/AddCrazyflie.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/AddCrazyflie.h] Error 1
[ 33%] Generating C++ code from crazyflie_driver/sendPacket.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:168: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/sendPacket.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/sendPacket.h] Error 1
[ 33%] Generating C++ code from crazyflie_driver/UploadTrajectory.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:176: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/UploadTrajectory.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/UploadTrajectory.h] Error 1
[ 34%] Generating C++ code from crazyflie_driver/Takeoff.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:183: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Takeoff.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Takeoff.h] Error 1
[ 34%] Generating C++ code from crazyflie_driver/GoTo.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:191: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/GoTo.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/GoTo.h] Error 1
[ 35%] Generating C++ code from crazyflie_driver/Land.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:198: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Land.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/Land.h] Error 1
[ 36%] Generating C++ code from crazyflie_driver/UpdateParams.srv
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ImportError: No module named 'em'
crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build.make:205: recipe for target '/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/UpdateParams.h' failed
make[2]: *** [/home/um/crazyswarm/ros_ws/devel/include/crazyflie_driver/UpdateParams.h] Error 1
make[2]: Target 'crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/build' not remade because of errors.
CMakeFiles/Makefile2:3619: recipe for target 'crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/all' failed
make[1]: *** [crazyflie_ros/crazyflie_driver/CMakeFiles/crazyflie_driver_generate_messages_cpp.dir/all] Error 2
[ 36%] Built target std_msgs_generate_messages_py
[ 36%] Built target geometry_msgs_generate_messages_py
[ 49%] Built target crazyflie_driver_generate_messages_py
[ 49%] Built target std_msgs_generate_messages_nodejs
[ 49%] Built target geometry_msgs_generate_messages_nodejs
[ 61%] Built target crazyflie_driver_generate_messages_nodejs
[ 61%] Built target std_msgs_generate_messages_lisp
[ 61%] Built target geometry_msgs_generate_messages_lisp
[ 73%] Built target crazyflie_driver_generate_messages_lisp
[ 73%] Built target std_msgs_generate_messages_eus
[ 73%] Built target geometry_msgs_generate_messages_eus
[ 84%] Built target crazyflie_driver_generate_messages_eus
make[1]: Target 'all' not remade because of errors.
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
make: Target 'default_target' not remade because of errors.
Invoking "make -j1 -k" failed
```

Looks like an issue with python imports. We *are* using a virtualenv, so here's the `pip freeze`:

```
absl-py==0.7.0
actionlib==1.11.13
angles==1.9.11
appdirs==1.4.0
astor==0.7.1
atari-py==0.1.7
bondpy==1.8.3
catkin==0.7.14
catkin-pkg==0.4.10
certifi==2018.11.29
-e git+https://github.com/bitcraze/crazyflie-clients-python.git@ec2a6b0d558772ba9b98c022054518cbf267addc#egg=cfclient&subdirectory=../../crazyflie-clients-python
cflib==0.1.7
chardet==3.0.4
Click==7.0
cloudpickle==0.7.0
cv-bridge==1.12.8
cycler==0.10.0
diagnostic-analysis==1.9.3
diagnostic-common-diagnostics==1.9.3
diagnostic-updater==1.9.3
dill==0.2.9
docutils==0.14
dynamic-reconfigure==1.5.50
future==0.17.1
gast==0.2.2
gencpp==0.6.0
geneus==2.2.6
genlisp==0.4.16
genmsg==0.5.11
gennodejs==2.0.1
genpy==0.6.7
glob2==0.6
grpcio==1.18.0
gym==0.11.0
h5py==2.9.0
idna==2.8
interactive-markers==1.11.4
joblib==0.13.1
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
laser-geometry==1.6.4
Markdown==3.0.1
matplotlib==2.1.2
message-filters==1.12.14
mpi4py==3.0.0
numpy==1.16.1
opencv-python==4.0.0.21
pandas==0.24.1
Pillow==5.4.1
pluginlib==1.11.3
progressbar2==3.39.2
protobuf==3.6.1
pyglet==1.3.2
PyOpenGL==3.1.0
pyparsing==2.3.1
PyQt5==5.12
PyQt5-sip==4.19.14
pyqtgraph==0.10.0
python-dateutil==2.8.0
python-qt-binding==0.3.4
python-utils==2.3.0
pytz==2018.9
pyusb==1.0.2
PyYAML==3.13
pyzmq==17.1.2
qt-dotgraph==0.3.11
qt-gui==0.3.11
qt-gui-cpp==0.3.11
qt-gui-py-common==0.3.11
requests==2.21.0
resource-retriever==1.12.4
rosbag==1.12.14
rosboost-cfg==1.14.4
rosclean==1.14.4
roscreate==1.14.4
rosdep==0.15.1
rosdistro==0.7.2
rosgraph==1.12.14
rosinstall==0.7.8
rosinstall-generator==0.1.14
roslaunch==1.12.14
roslib==1.14.4
roslint==0.11.0
roslz4==1.12.14
rosmake==1.14.4
rosmaster==1.12.14
rosmsg==1.12.14
rosnode==1.12.14
rosparam==1.12.14
rospkg==1.1.7
rospy==1.12.14
rosservice==1.12.14
rostest==1.12.14
rostopic==1.12.14
rosunit==1.14.4
roswtf==1.12.14
rqt-action==0.4.9
rqt-bag==0.4.12
rqt-bag-plugins==0.4.12
rqt-console==0.4.8
rqt-dep==0.4.9
rqt-graph==0.4.9
rqt-gui==0.5.0
rqt-gui-py==0.5.0
rqt-image-view==0.4.13
rqt-launch==0.4.8
rqt-logger-level==0.4.8
rqt-moveit==0.5.7
rqt-msg==0.4.8
rqt-nav-view==0.5.7
rqt-plot==0.4.8
rqt-pose-view==0.5.8
rqt-publisher==0.4.8
rqt-py-common==0.5.0
rqt-py-console==0.4.8
rqt-reconfigure==0.4.10
rqt-robot-dashboard==0.5.7
rqt-robot-monitor==0.5.8
rqt-robot-steering==0.5.9
rqt-runtime-monitor==0.5.7
rqt-rviz==0.5.10
rqt-service-caller==0.4.8
rqt-shell==0.4.9
rqt-srv==0.4.8
rqt-tf-tree==0.5.8
rqt-top==0.4.8
rqt-topic==0.4.10
rqt-web==0.4.8
rviz==1.12.16
scipy==1.2.1
seaborn==0.9.0
sensor-msgs==1.12.7
six==1.12.0
smach==2.0.1
smach-ros==2.0.1
smclib==1.8.3
stable-baselines==2.4.1
tensorboard==1.12.2
tensorflow-gpu==1.12.0
termcolor==1.1.0
tf==1.11.9
tf-conversions==1.11.9
tf2-kdl==0.5.20
tf2-py==0.5.20
tf2-ros==0.5.20
topic-tools==1.12.14
tqdm==4.31.1
urllib3==1.24.1
vcstools==0.1.40
vispy==0.5.3
Werkzeug==0.14.1
wstool==0.1.17
xacro==1.11.3
zmq==0.0.0
```

**Comment by arxk9** [comment]
Ok so i tried a `pip install em`, and now I get this:

```
File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'Interpreter'
```

**Comment by whoenig** [comment]
This seems like a generic ROS problem, perhaps this will help: https://answers.ros.org/question/257331/python-module-empy-missing-tutorials/ ?

**Comment by arxk9** [comment]
Ok thank you! We fixed the issue by using system python instead of a virtualenv.
