### ISSUE TITLE
python confusion with the * library

### ISSUE THREAD

**Issue by EdwinMeriaux** [USC-ACTLab/crazyswarm#184]
So I am trying out the simulation from https://crazyswarm.readthedocs.io/en/latest/installation.html#simulation-only

I followed simulation steps and everytime I run: python figure8_csv.py --sim

I received the following error:

Traceback (most recent call last):
  File "figure8_csv.py", line 5, in <module>
    from pycrazyswarm import *
  File "/home/edwin-pcp/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/piecewise.py", line 1, in <module>
    from .cfsim import cffirmware as firm
  File "/home/edwin-pcp/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/cfsim/cffirmware.py", line 28, in <module>
    _cffirmware = swig_import_helper()
  File "/home/edwin-pcp/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/cfsim/cffirmware.py", line 24, in swig_import_helper
    _mod = imp.load_module('_cffirmware', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/edwin-pcp/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/cfsim/_cffirmware.so: undefined symbol: PyInstance_Type

What am I doing wrong? Or is there an issue in the downloaded file is inaccurate?

Thank you for any help

**Comment by EdwinMeriaux** [comment]
I apologize I figured out my mistake. I apologize for wasting anyone's time.
