### ISSUE TITLE
firmware update failed when running `launchBootloader.py`

### ISSUE THREAD

**Issue by RandyChen233** [USC-ACTLab/crazyswarm#673]
Hi,

I am getting the following error when running this line:
`python crazyradio-firmware/usbtools/launchBootloader.py`

the error reads:

`Traceback (most recent call last):
  File "crazyradio-firmware/usbtools/launchBootloader.py", line 95, in <module>
    sys.exit(launchBootloader(True))
  File "crazyradio-firmware/usbtools/launchBootloader.py", line 42, in launchBootloader
    dev= findDevice(0x1915, 0x7777)
  File "crazyradio-firmware/usbtools/launchBootloader.py", line 33, in findDevice
    busses = usb.busses()
  File "/home/randychen233/.local/lib/python3.8/site-packages/usb/legacy.py", line 355, in busses
    sorted(core.find(find_all=True), key=lambda d: d.bus),
  File "/home/randychen233/.local/lib/python3.8/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available`

**Comment by jpreiss** [comment]
This does not sound Crazyswarm-specific. Try asking in https://github.com/orgs/bitcraze/discussions
